name: "Post to Bluesky"

on:
  schedule:
    - cron: "18 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - run: npm run build
      - name: Send post
        run: npm start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          AWS_S3_LATEST_POST_BUCKET: ${{secrets.AWS_S3_LATEST_POST_BUCKET}}
          AWS_S3_LATEST_POST_KEY: ${{secrets.AWS_S3_LATEST_POST_KEY}}
          AWS_S3_REGION: ${{secrets.AWS_S3_REGION}}
          DRY_RUN: ${{secrets.DRY_RUN}}
          OPENAI_KEY: ${{secrets.OPENAI_KEY}}
